#!/bin/bash

export GOOGLE_CLOUD_PROJECT="<YOUR-GOOGLE-CLOUD-PROJECT>"
export GOOGLE_CLOUD_REGION="<YOUR-GOOGLE-CLOUD-REGION>"
export SWAGGERHUB_OWNER="<YOUR-SWAGGERHUB-OWNER>"
export SWAGGERHUB_API_KEY="<YOUR-SWAGGERHUB-API-KEY>"